/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author Usuario
 */
public class Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atras = new javax.swing.JButton();
        Atras2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Atras1 = new javax.swing.JButton();
        txtnicknameconfing = new javax.swing.JTextField();
        txtcorreoconfing = new javax.swing.JTextField();
        txtpasswordconfing = new javax.swing.JTextField();

        Atras.setBackground(new java.awt.Color(0, 153, 153));
        Atras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atras");
        Atras.setActionCommand("Back");

        Atras2.setBackground(new java.awt.Color(0, 153, 153));
        Atras2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atras2.setForeground(new java.awt.Color(255, 255, 255));
        Atras2.setText("Atras");
        Atras2.setActionCommand("Back");

        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIGURACION");

        Aceptar.setBackground(new java.awt.Color(0, 204, 153));
        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Atras1.setBackground(new java.awt.Color(0, 204, 153));
        Atras1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atras1.setForeground(new java.awt.Color(255, 255, 255));
        Atras1.setText("Atras");
        Atras1.setActionCommand("Back");
        Atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras1ActionPerformed(evt);
            }
        });

        txtnicknameconfing.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de usuario"));
        txtnicknameconfing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicknameconfingActionPerformed(evt);
            }
        });

        txtcorreoconfing.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo electronico"));
        txtcorreoconfing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoconfingActionPerformed(evt);
            }
        });

        txtpasswordconfing.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        txtpasswordconfing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordconfingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Atras1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Aceptar)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcorreoconfing, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnicknameconfing, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpasswordconfing, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(txtnicknameconfing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtcorreoconfing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtpasswordconfing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Atras1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnicknameconfingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicknameconfingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicknameconfingActionPerformed

    private void txtcorreoconfingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoconfingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoconfingActionPerformed

    private void txtpasswordconfingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordconfingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordconfingActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        String nickname = txtnicknameconfing.getText().trim();
        String correo = txtcorreoconfing.getText().trim();
        String password = txtpasswordconfing.getText().trim();

        // Verificar si algún campo está vacío
        if (nickname.isEmpty() || correo.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si hay campos vacíos
        }

        // Mensaje de éxito si todos los campos están llenos
        javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AceptarActionPerformed

    private void Atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras1ActionPerformed
        // TODO add your handling code here:
        // Crear una nueva instancia de MenuUsuario
        MenuUsuario menuUsuario = new MenuUsuario();
        menuUsuario.setVisible(true); // Mostrar la ventana de menú usuario

        // Cerrar la ventana actual
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_Atras1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Atras1;
    private javax.swing.JButton Atras2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtcorreoconfing;
    private javax.swing.JTextField txtnicknameconfing;
    private javax.swing.JTextField txtpasswordconfing;
    // End of variables declaration//GEN-END:variables
}
