/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author Usuario
 */
public class ConfiguracionAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracionAdmin
     */
    public ConfiguracionAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nickadministrador = new javax.swing.JTextField();
        correcoadmin = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Atrasadmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIGURACION");

        setBackground(new java.awt.Color(0, 204, 153));

        nickadministrador.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de usuario"));
        nickadministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickadministradorActionPerformed(evt);
            }
        });

        correcoadmin.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo electronico"));
        correcoadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correcoadminActionPerformed(evt);
            }
        });

        Aceptar.setBackground(new java.awt.Color(0, 204, 153));
        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Atrasadmin.setBackground(new java.awt.Color(0, 204, 153));
        Atrasadmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atrasadmin.setForeground(new java.awt.Color(255, 255, 255));
        Atrasadmin.setText("Atras");
        Atrasadmin.setActionCommand("Back");
        Atrasadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasadminActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONFIGURACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Atrasadmin)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Aceptar)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correcoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nickadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(nickadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(correcoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(27, 27, 27)
                .addComponent(Atrasadmin))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nickadministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickadministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickadministradorActionPerformed

    private void correcoadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correcoadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correcoadminActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        String nickname = nickadministrador.getText().trim();
        String correo = correcoadmin.getText().trim();

        // Verificar si algún campo está vacío
        if (nickname.isEmpty() || correo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si hay campos vacíos
        }

        // Mensaje de éxito si todos los campos están llenos
        javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AceptarActionPerformed

    private void AtrasadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasadminActionPerformed
        MenuAdmin menuAdmin = new MenuAdmin(); // Crear la ventana de MenuAdmin
        menuAdmin.setVisible(true); // Mostrar la ventana de MenuAdmin
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_AtrasadminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Atrasadmin;
    private javax.swing.JTextField correcoadmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nickadministrador;
    // End of variables declaration//GEN-END:variables
}
