/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author Usuario
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Edadusuario = new javax.swing.JTextField();
        Nicknameusuario = new javax.swing.JTextField();
        Nombreusuario2 = new javax.swing.JTextField();
        Correousuario = new javax.swing.JTextField();
        celularusuario = new javax.swing.JTextField();
        passwordusuario = new javax.swing.JPasswordField();
        Volver = new javax.swing.JButton();
        Confirmar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE USUARIOS");

        Edadusuario.setForeground(new java.awt.Color(0, 102, 102));
        Edadusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        Edadusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadusuarioActionPerformed(evt);
            }
        });

        Nicknameusuario.setForeground(new java.awt.Color(0, 102, 102));
        Nicknameusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de usuario"));
        Nicknameusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NicknameusuarioActionPerformed(evt);
            }
        });

        Nombreusuario2.setForeground(new java.awt.Color(0, 102, 102));
        Nombreusuario2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        Nombreusuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombreusuario2ActionPerformed(evt);
            }
        });

        Correousuario.setForeground(new java.awt.Color(0, 102, 102));
        Correousuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        Correousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreousuarioActionPerformed(evt);
            }
        });

        celularusuario.setForeground(new java.awt.Color(0, 102, 102));
        celularusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero celular"));
        celularusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularusuarioActionPerformed(evt);
            }
        });

        passwordusuario.setForeground(new java.awt.Color(0, 102, 102));
        passwordusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        passwordusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordusuarioActionPerformed(evt);
            }
        });

        Volver.setText("VOLVER");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        Confirmar.setText("ACEPTAR");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(celularusuario)
                        .addComponent(Correousuario)
                        .addComponent(Nombreusuario2)
                        .addComponent(Edadusuario)
                        .addComponent(Nicknameusuario)
                        .addComponent(passwordusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Confirmar)
                        .addGap(50, 50, 50)
                        .addComponent(Volver)))
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Nombreusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edadusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(Correousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(celularusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nicknameusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(Confirmar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        // Crear una nueva instancia de la ventana Login
    Login login = new Login();
    login.setVisible(true); // Mostrar la ventana de login

    // Cerrar la ventana de registro
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        
    }//GEN-LAST:event_VolverActionPerformed

    private void Nombreusuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombreusuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombreusuario2ActionPerformed

    private void EdadusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadusuarioActionPerformed

    private void CorreousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreousuarioActionPerformed

    private void celularusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularusuarioActionPerformed

    private void NicknameusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NicknameusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NicknameusuarioActionPerformed

    private void passwordusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordusuarioActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        // TODO add your handling code here:
         // Obtener los valores ingresados por el usuario
    String nombre = Nombreusuario2.getText().trim();
    String edad = Edadusuario.getText().trim();
    String correo = Correousuario.getText().trim();
    String celular = celularusuario.getText().trim();
    String nickname = Nicknameusuario.getText().trim();
    String password = new String(passwordusuario.getPassword()).trim();

    // Verificar si algún campo está vacío
    if (nombre.isEmpty() || edad.isEmpty() || correo.isEmpty() || celular.isEmpty() || nickname.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; // Salir del método si hay campos vacíos
    }

    // Mostrar mensaje de confirmación
    javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JTextField Correousuario;
    private javax.swing.JTextField Edadusuario;
    private javax.swing.JTextField Nicknameusuario;
    private javax.swing.JTextField Nombreusuario2;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField celularusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordusuario;
    // End of variables declaration//GEN-END:variables
}
